Fix social image URL variables in meta tag
ft-interactive/starter-kit pull request #281
Opened 2020-12-09 16:34 UTC by joannaskao

2020-12-09 16:51 UTC, emmalewis requested changes

2020-12-09 16:51 UTC, emmalewis commented on app/index.html
> +    <meta name="twitter:image" content="<%= htmlWebpackPlugin.options.context.twitterImage || htmlWebpackPlugin.options.context.socialImage || htmlWebpackPlugin.options.context.mainImageUrl %>" />
I know `htmlWebpackPlugin.options.context.mainImageUrl` is used elsewhere in this file, but looking at `config/article.js` I think it should actually be `htmlWebpackPlugin.options.context.mainImage.url`?

2020-12-09 18:17 UTC, joannaskao commented on app/index.html
> +    <meta name="twitter:image" content="<%= htmlWebpackPlugin.options.context.twitterImage || htmlWebpackPlugin.options.context.socialImage || htmlWebpackPlugin.options.context.mainImageUrl %>" />
Ooh good catch, thanks! Because of this also realised another thing we used to historically have needed to be taken out. Thanks!

2020-12-16 11:42 UTC, emmalewis approved these changes
Looks good! LGTM

2020-12-16 11:44 UTC, merged