Scrolly changes
ft-interactive/starter-kit pull request #335
Opened 2024-05-10 21:37 UTC by sdl60660

Corresponds with changes to vs-components here: https://github.com/ft-interactive/vs-components/pull/71 (as well as changes earlier this week), so the vs-components PR should be cleaned up/merged before this is reviewed/merged

* Bumping `g-components` version
* Bumping `vs-components` version (though this will need to change when that's actually released)
* Adding helper function (`constructScrollySteps`) for constructing scrolly steps by zipping together ArchieML doc data anyway `waypoints` or `highlights` data and turning the inner content into ingestible cards (we have some version of this helper in every project on a per-wrapper basis right now)
* Adding template `ScrollySection` wrapper component in `sections`
* Adding `BodyText`/`Headline` components that we frequently re-use, but need customization for almost every project

2024-05-13 09:30 UTC, emmalewis requested changes
Thanks for adding this Sam. It mostly looks good although I'm very far removed from the ArchieML stuff and day to day project work at this point, so probably worth getting a review from Dan / Justine / Peter too. I have added one comment about using vs-components TopperText for the Headline - that component should be set up for any configuration you need, but if not then please let me know.

2024-05-13 09:30 UTC, emmalewis commented on app/components/Headline/index.jsx
> +export default Headline;
Please can we use the vs-components TopperText component for this?

2024-05-13 14:35 UTC, emmalewis commented on app/components/Headline/index.jsx
> +export default Headline;
We should be able to use it. Hopefully we could just remove this and [replace line 35 in the map data to steps util](https://github.com/ft-interactive/starter-kit/pull/335/files#diff-83943a7a9cc83b7d060d88a9909fb8c92be0865ef75b68aa7ff943bc27fca6d1R35) with the TopperText component

2024-05-16 12:06 UTC, pandringa reviewed
A couple of notes here but on the whole this seems good! I'll be glad to not copy these over from project to project anymore

2024-05-16 12:06 UTC, pandringa commented on app/util/text.jsx
> +export function insertSpans(text, highlights, options = { p: true }) {
I vaguely call an edge-case when I wrote this function:  I'm not sure it handles overlapping highlights very well. Could you make a note of that in the comments here? (Or, maybe we can throw an error or even attempt to rewrite the `const output = matches.reduce(` function on line 35 below to fix that bug?)

See below here - I've added highlights to both "overlapping" and "with some overlapping" 

<img width="431" alt="Screenshot 2024-05-16 at 13 04 17" src="https://github.com/ft-interactive/starter-kit/assets/3749412/c95f0fb5-381e-4618-9f28-f8bad99b73b5">

2024-05-20 18:41 UTC, sdl60660 commented on app/components/BodyText/index.jsx
> +      /* eslint-disable react/no-array-index-key */
cool, yeah this seems to back that up: https://stackoverflow.com/a/42171014

I'll do that

2024-05-20 18:43 UTC, sdl60660 commented on app/components/BodyText/index.jsx
> +      /* eslint-disable react/no-array-index-key */
actually, the values aren't guaranteed to be unique (e.g. there could be two headers with the same text), so going to do this as a combo of the value and index

2024-05-20 18:47 UTC, sdl60660 commented on app/components/BodyText/index.jsx
> +              media={{ videoSrc: videoConfig.videoSrc, image: videoConfig.image }}
Hmm, I'm a little wary of passing in an object with a bunch of extra data (that also doesn't match the `propTypes` definition for the Video components), but would defer to you a bit here. Happy to just do that if you think it makes more sense than what's in there now (`media={{ videoSrc, image }}`)

2024-05-20 19:01 UTC, sdl60660 commented on app/components/BodyText/index.jsx
> +      }));
hmm, I put this in for the links, but would we only want this on links? seems like we might want it (optionally) for all body text, right?

2024-05-20 19:10 UTC, sdl60660 commented on app/util/map-data-to-steps.jsx
> +    const { stepVerticalAlignment = null, stepGapSize = null } = matchingWaypoint;
yeah it was just a way of either grabbing them from the objet or defaulting them to null, though as you say, there are very few cases where it would matter whether they were null or undefined. in theory, having them written explicitly here, instead of just passed through the `...matchingWaypoint` spread operator, also serves as a reminder that these values can be adjusted/fed into ScrollSteps as props, though that's also accomplished through documentation or could be in a comment, etc

2024-05-20 19:12 UTC, sdl60660 commented on app/util/text.jsx
> +export function insertSpans(text, highlights, options = { p: true }) {
yeah, I'll give this a look. on a couple of projects, I've modified this a little to accept an `indexStep` value as well, scoping it to a particular step, which maybe a good addition? (though in practice is a little hard to use until the very end of a project, once we done with edits)

2024-05-21 10:14 UTC, danclark18 commented on app/app.jsx
> +      <LoadBlocker contentLoaded={contentLoaded} blurTransition={false}>
Do we think we should include the LoadBlocker component by default? I feel like most of our projects we won't need it

2024-05-21 10:14 UTC, danclark18 commented on app/components/BodyText/styles.scss
> +.body-text {
I wonder if this `extra-margin` is something we could include in vs-components? Although we'd have to add it to every visual, or perhaps create a `VisualWrapper` or something like that

2024-06-10 10:54 UTC, sdl60660 commented on app/app.jsx
> +      <LoadBlocker contentLoaded={contentLoaded} blurTransition={false}>
(circling back on all of this): you're right, going to remove

2024-06-10 14:24 UTC, sdl60660 commented on app/util/text.jsx
> +export function insertSpans(text, highlights, options = { p: true }) {
added something on a branch that I'll merge in a minute

2024-06-11 15:00 UTC, danclark18 commented
lgtm @sdl60660! thanks for sorting this

2024-06-11 17:25 UTC, pandringa reviewed
On the whole this seems really good to me! The only important notes are a couple of details about how the `switch...case` statements interact with the ArchieML parser, but the rest are mostly thoughts or light suggestions - feel free to take them or leave them as you want.

2024-06-11 17:25 UTC, pandringa commented on app/components/ArchieStoryBody/index.jsx
> +            />
One thing I often do in these big `switch...case` blocks is add `{...component}` to the props, so that you can do things like `caption: tktktk` and `alt: tktktk` in the Google Doc and have it automatically passed through to the component. (It might be worth demonstrating this in the example file, too?)

2024-06-11 17:25 UTC, pandringa commented on app/components/ArchieStoryBody/index.jsx
> +        case 'inline-image':
I would make this just `image` - I _think_ the ArchieML parser (at least versions I've written before) has used `inline-` as a special prefix that passes the components down within the text paras. (Basically, `inline-image` and `inline-video` blocks are _within_ the text column, while `image` and `video` blocks are `fullGridWidth`.)

e.g. https://github.com/ft-interactive/ig-west-bank/blob/main/app/app.jsx#L131

2024-06-11 17:25 UTC, pandringa commented on app/components/ArchieStoryBody/index.jsx
> +        default:
Could you add a case for `video` as well? (I usually wrap it in a `<LazyLoad>` by default, just to avoid the browser slowing down the initial load with the mp4 download too.)

2024-06-11 17:25 UTC, pandringa commented on app/components/BodyText/index.jsx
> +        case 'video': {
This is the inverse of the above - unless you've adapted the ArchieML parser script, this probably should be `inline-video` (since the plain `video` type won't get passed in via the `paras` text list).

2024-06-11 17:25 UTC, pandringa commented on app/components/BodyText/index.jsx
> +        case 'image': {
```suggestion
        case 'inline-image': {
```

2024-06-11 17:25 UTC, pandringa commented on app/components/BodyText/index.jsx
> +          if (!imageConfig) return null;
Would it be worth adding a similar approach to the `IMAGES` list in the ArchieStoryBody file?

Another option (although definitely not required here, could easily be a separate PR) would be to structure the assets directory to automatically list the content. I usually add an `assets/index.js` file that uses `import.meta.glob` to read all of the image files and then export them, so you can do
```
import { images } from '../assets/';
...
const imageConfig = images[value]
```
e.g. something like this https://github.com/ft-interactive/ig-west-bank/blob/main/app/assets/images/index.jsx

2024-06-11 17:25 UTC, pandringa commented on app/util/text.jsx
> +  }
Ha, hacky but fair enough! I think this seems fine to me.

2024-06-11 17:25 UTC, pandringa commented on config/data.json
> +{
I'm not _totally_ sure we want to leave this file here — right now, the parser uses the presence of this file to decide whether data-fetching should happen via `npm run data` or on server start. 

I personally think it would be better to default to no `data.json` file (fetch-at-build-time mode), then let the user opt-in to data caching via `npm run data` — rather than need to remember to delete this file if you want to live-reload the data.

(This isn't an incredibly strongly-held opinion, just a thought.)

2024-06-12 08:42 UTC, emmalewis approved these changes
No additional comments from me besides some of the things that Peter and Dan have highlighted.

2024-06-12 10:18 UTC, sdl60660 commented on app/components/ArchieStoryBody/index.jsx
> +        default:
good call, done. added it to the template doc too

2024-06-12 10:28 UTC, sdl60660 commented on app/components/ArchieStoryBody/index.jsx
> +        default:
actually having some issues that I think are a vs-components issue that I'll bring up with you all in a minute

2024-06-12 10:30 UTC, sdl60660 commented on app/util/text.jsx
> +  }
chatted with Dan about whether to make this a console warning or an error and I think an error makes more sense here? particularly since it's in starter-kit, so we can always just disable

2024-06-12 10:59 UTC, sdl60660 commented on config/data.json
> +{
ok we talked about this and cleared the `data.json`/are generally happy with the way we've set things up in terms of defaults on the `data.js` function

2024-06-12 11:09 UTC, sdl60660 commented on app/components/ArchieStoryBody/index.jsx
> +            />
all set on this

2024-06-12 11:09 UTC, sdl60660 commented on app/components/BodyText/index.jsx
> +          if (!imageConfig) return null;
we're going to leave this for a separate PR

2024-06-12 11:09 UTC, merged