Refactor image/video asset imports
ft-interactive/starter-kit pull request #341
Opened 2024-06-12 15:56 UTC by pandringa

This adds new import helpers to make it easier to require image and video assets. Instead of needing the developer to manually add lines like this:
```
import MyImage from '../media/my_image.jpg';
...
<Image src={MyImage} alt="alt tk" sizes="..." />
```

You can instead do:
```
import images from '../media/images';
<Image {...images.my_image} />
```

It works by using `meta.import.glob` to automatically discover all images and videos in their respective folders, and format them into objects and arrays based on their filenames. Images for different breakpoints should be named like `<name>.S.jpg`, `<name>.M.jpg`, `<name>.L.jpg` etc, while images that are meant to be in an array (e.g. for a side-by-side image pair) can be `<name>.0.jpg`, `<name>.1.jpg`. Where necessary these can be combined: `<name>.0.S.jpg`, etc

This is particularly useful for the ArchieML parsing convention, since you can simply drop image assets into the folder then reference them in your Google Doc like `image: my_image`. This will automatically load in the image props (including size variants) that correspond with that name, saving you a good deal of effort in needing to connect up the code and the Google doc.

2024-06-12 15:58 UTC, pandringa commented on package.json
> +    "@ft-interactive/vs-components": "^5.0.0-canary.7",
We'll hold this PR until vs-components v5.0.0 is fully released

2024-06-12 15:59 UTC, pandringa commented on app/util/prop-types.js
> -  ).isRequired,
I've removed these since we cut them from `article.js`, but I'm happy to restore them (as optional) if you want.

2024-06-19 13:52 UTC, emmalewis requested changes
This is a really interesting idea. I've left some notes, but it's mostly questions.

2024-06-19 13:52 UTC, emmalewis commented on app/components/BodyText/index.jsx
>          case 'subhed':
`subhed` typo should be `subhead`

2024-06-19 13:52 UTC, emmalewis commented on app/components/ArchieStoryBody/index.jsx
> -          return <h2 key={i}>{component.value}</h2>;
Was this intended to be removed?

2024-06-19 13:52 UTC, emmalewis commented on app/media/util.js
> +export const ALT = {};
I feel like there's a risk that this might be quite easy to forget / overlook, which would presumably result in us having images without alt text? Are there any ways we could enforce this?

2024-06-19 13:52 UTC, emmalewis commented on app/media/images/index.js
> +const images = sortFiles(import.meta.glob('./*.{png,jpg,jpeg,gif}', { eager: true })).reduce(
Do we want to include webp here?

2024-06-19 13:52 UTC, emmalewis commented on app/media/images/index.js
> +      k.match(/\/([-_\w]+)\.([0-9]+)?\.?([SMLX]+)?\.?(png|jpe?g)$/) || [];
Also should we include gif and webp here?

2024-06-19 14:44 UTC, pandringa commented on app/components/BodyText/index.jsx
>          case 'subhed':
So this was actually intentional - I've always used `hed` and `subhed` as keys for headlines in our ArchieML doc (out of convention), but I realize it's a bit confusing. Maybe I'll update it so that either value is accepted?

2024-06-19 14:45 UTC, emmalewis commented on app/components/BodyText/index.jsx
>          case 'subhed':
Oh that's fine - if it's intentional and conventional then that's fine - I haven't worked on an ArchieML project so very happy to go with what works for the team (especially as this code wasn't actually in side this PR)

2024-06-19 14:46 UTC, pandringa commented on app/components/ArchieStoryBody/index.jsx
> -          return <h2 key={i}>{component.value}</h2>;
Yes - it's just not super clearly documented! All the "inline" types (text, subhed, inline-image, inline-video — which all sit inside the text column) are rendered as text blocks by the `BodyText` component. This `ArchieStoryBody` block only needs to render `fullGridWidth` or fullscreen components, since the text ones are all handled inside `<BodyText>`.

2024-06-19 14:51 UTC, pandringa commented on app/media/util.js
> +export const ALT = {};
For the most part, we've set `PropTypes.string.isRequired` on any component with alt text — so usually get a bunch of noisy console warnings telling you when you forget it. (Towards the end of each project, I usually go through and address all the warnings and make sure each component has alt text.)

There's three different ways you could add alt text (each value in this list overrides the previous):
- In this object
- Inside the ArchieML doc like `image: my_image // alt: My alt text` 
```
image: my_image
alt: My alt text
```
- Directly on the component, like `<Image {...images.my_image} alt="My image" />`

I think most projects have a mix and match of these approaches — it's often handy to include them in the document so that they get subbed, but sometimes you need to override here or even inline (e.g. in a more bespoke layout). As a result, I think enforcing alt text at a per-component basis with PropTypes is better than doing it here.

2024-06-19 14:53 UTC, emmalewis commented on app/media/util.js
> +export const ALT = {};
Yep that all makes sense, thanks for taking the time to explain.

2024-06-19 14:54 UTC, pandringa commented on app/media/images/index.js
> +const images = sortFiles(import.meta.glob('./*.{png,jpg,jpeg,gif}', { eager: true })).reduce(
We could! I didn't add it because right now, the Origami Image Service only supports `png`, `jpg`, `gif` and `svg` — and by default, we optimize our image sizes using it's api.

If we supported webp here, it would potentially break those resizes (and in a slightly annoying way, only on prod) — so I personally think it's better to make the developer manually add support for webp and set `imageService: false` on the default image props. (Or maybe do something smart and set that prop only if type is `webp`?)

2024-06-19 14:56 UTC, emmalewis commented on app/media/images/index.js
> +const images = sortFiles(import.meta.glob('./*.{png,jpg,jpeg,gif}', { eager: true })).reduce(
Makes sense, thanks

2024-07-10 14:54 UTC, emmalewis approved these changes
As with the vs-components I'd prefer InlineGraphic to be named differently to identify it as Ai2html, but otherwise this looks good!

2024-07-17 13:51 UTC, merged